# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroups',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('page_1', models.IntegerField()),
                ('page_2', models.IntegerField()),
                ('page_3', models.IntegerField()),
                ('page_5', models.IntegerField()),
                ('page_6', models.IntegerField()),
                ('page_7', models.IntegerField()),
                ('page_8', models.IntegerField()),
                ('page_9', models.IntegerField()),
                ('page_10', models.IntegerField()),
                ('page_11', models.IntegerField()),
                ('page_12', models.IntegerField()),
                ('page_13', models.IntegerField()),
                ('page_14', models.IntegerField()),
                ('page_15', models.IntegerField()),
                ('page_16', models.IntegerField()),
                ('page_18', models.IntegerField()),
                ('page_19', models.IntegerField()),
                ('page_20', models.IntegerField()),
                ('page_21', models.IntegerField()),
                ('page_22', models.IntegerField()),
                ('page_23', models.IntegerField()),
                ('page_24', models.IntegerField()),
                ('page_25', models.IntegerField()),
                ('page_26', models.IntegerField()),
                ('page_27', models.IntegerField()),
                ('page_28', models.IntegerField()),
                ('page_36', models.IntegerField()),
                ('page_38', models.IntegerField()),
                ('page_39', models.IntegerField()),
                ('page_40', models.IntegerField()),
                ('page_41', models.IntegerField()),
                ('page_42', models.IntegerField()),
                ('page_43', models.IntegerField()),
                ('page_44', models.IntegerField()),
                ('page_45', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocContact',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bloc_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocContactLocations',
            fields=[
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=7)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('toll_free_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email1', models.CharField(blank=True, max_length=200, null=True)),
                ('email2', models.CharField(blank=True, max_length=200, null=True)),
                ('google_map_address', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('title_fr', models.CharField(max_length=200)),
                ('image_name_fr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bloc_contact_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocDocuments',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bloc_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocDocumentsDocuments',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bloc_documents_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocEditor',
            fields=[
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('content_fr', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bloc_editor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocFlickrGallery',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('show_amount', models.IntegerField(blank=True, null=True)),
                ('photoset_id', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'bloc_flickr_gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocRepertoire',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bloc_repertoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocRepertoireRepertoire',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bloc_repertoire_repertoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocSocial',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('facebook_send', models.IntegerField()),
                ('facebook_like', models.IntegerField()),
                ('twitter_button', models.IntegerField()),
                ('plusone_button', models.IntegerField()),
            ],
            options={
                'db_table': 'bloc_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlocYoutube',
            fields=[
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('video', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bloc_youtube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('name_fr', models.TextField()),
                ('content_fr', models.TextField(blank=True, null=True)),
                ('alias', models.TextField()),
                ('changeable', models.IntegerField()),
                ('allow_subpages', models.IntegerField()),
            ],
            options={
                'db_table': 'cats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlickrUsers',
            fields=[
                ('flickr_user_id', models.TextField(primary_key=True, serialize=False)),
                ('flickr_reference_name', models.TextField()),
            ],
            options={
                'db_table': 'flickr_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('validated', models.IntegerField()),
                ('date_validation', models.DateTimeField()),
                ('datetime_last_newsletter', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mailing_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModArticles',
            fields=[
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField()),
                ('facebook_like', models.IntegerField()),
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('content_fr', models.TextField()),
                ('image_name_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('url_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('page_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModContacts',
            fields=[
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mod_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModContactsContacts',
            fields=[
                ('parent_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('department_fr', models.TextField()),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('tel_1', models.TextField()),
                ('tel_2', models.TextField()),
                ('tel_3', models.TextField()),
                ('tel_2_type', models.TextField()),
                ('tel_3_type', models.TextField()),
                ('fax', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'mod_contacts_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModContent',
            fields=[
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('bloc', models.TextField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModCustom',
            fields=[
                ('path', models.TextField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_custom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModDocuments',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('category', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('title_fr', models.TextField()),
                ('description_fr', models.TextField()),
            ],
            options={
                'db_table': 'mod_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModDocumentsCats',
            fields=[
                ('rank', models.IntegerField()),
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mod_documents_cats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModEvents',
            fields=[
                ('page_id', models.IntegerField()),
                ('date', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('days_start_display', models.SmallIntegerField()),
                ('days_end_display', models.SmallIntegerField()),
                ('location_url', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('date_publication', models.DateTimeField()),
                ('facebook_like', models.IntegerField()),
                ('calendar_only', models.IntegerField()),
                ('subscriptions_enabled', models.IntegerField()),
                ('active', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('content_fr', models.TextField()),
                ('content_short_fr', models.TextField()),
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('location_fr', models.TextField()),
                ('image_name_fr', models.TextField()),
            ],
            options={
                'db_table': 'mod_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModEventsDateRanges',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_events_date_ranges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModLinks',
            fields=[
                ('url', models.CharField(max_length=255)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('page_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModLinksCats',
            fields=[
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('page_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_links_cats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModNews',
            fields=[
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField()),
                ('date_display_start', models.DateField()),
                ('date_display_end', models.DateField()),
                ('facebook_like', models.IntegerField()),
                ('display_on_home_page', models.IntegerField()),
                ('title_fr', models.TextField(primary_key=True, serialize=False)),
                ('content_fr', models.TextField()),
                ('content_short_fr', models.TextField()),
                ('image_name_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('url_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('page_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModProfiles',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=7)),
                ('telephone1', models.CharField(max_length=20)),
                ('telephone2', models.CharField(max_length=20)),
                ('toll_free', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=255)),
                ('google_maps', models.TextField()),
                ('facebook_page', models.CharField(max_length=255)),
                ('twitter_page', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('cognibox', models.IntegerField()),
                ('cognibox_text', models.CharField(max_length=255)),
                ('iso', models.IntegerField()),
                ('iso_text', models.CharField(max_length=255)),
                ('rbq', models.IntegerField()),
                ('rbq_text', models.CharField(max_length=255)),
                ('bsdq', models.IntegerField()),
                ('bsdq_text', models.CharField(max_length=255)),
                ('merx', models.IntegerField()),
                ('merx_text', models.CharField(max_length=255)),
                ('autre_text', models.TextField()),
                ('equipments', models.TextField()),
                ('annual_employe_number', models.CharField(max_length=200)),
                ('seasonal_employe_number', models.CharField(max_length=200)),
                ('active', models.IntegerField()),
                ('nation', models.TextField()),
                ('neq', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('mrc', models.TextField()),
                ('loc_ss', models.TextField()),
                ('fondation', models.TextField()),
                ('chiffres', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mod_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModProfilesAchievements',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('period', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=15)),
                ('client_name', models.CharField(max_length=255)),
                ('flickr_photoset_id', models.CharField(max_length=100)),
                ('flickr_user_id', models.IntegerField()),
                ('flickr_tag', models.CharField(max_length=100)),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_profiles_achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModProfilesCategories',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
                ('cat_url', models.CharField(max_length=255)),
                ('parent_id', models.SmallIntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_profiles_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModProfilesCats',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('id_category', models.SmallIntegerField()),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_profiles_cats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModProfilesContacts',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_title', models.CharField(max_length=255)),
                ('contact_telephone1', models.CharField(max_length=100)),
                ('contact_telephone2', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=200)),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_profiles_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModProfilesReferences',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_title', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('telephone1', models.CharField(max_length=100)),
                ('telephone2', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=255)),
                ('doc', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mod_profiles_references',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('site_name_fr', models.TextField(primary_key=True, serialize=False)),
                ('meta_keywords_fr', models.TextField()),
                ('meta_description_fr', models.TextField()),
                ('youtube_user', models.TextField()),
                ('newsletter_last_sending', models.DateTimeField()),
            ],
            options={
                'db_table': 'options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('title_fr', models.TextField()),
                ('name_fr', models.TextField(primary_key=True, serialize=False)),
                ('content_fr', models.TextField(blank=True, null=True)),
                ('module', models.TextField()),
                ('linkable', models.IntegerField()),
                ('placement', models.IntegerField()),
                ('admin_only', models.IntegerField()),
                ('alias', models.TextField()),
                ('changeable', models.IntegerField()),
                ('allow_subpages', models.IntegerField()),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('parent_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'structure',
                'managed': False,
            },
        ),
    ]
